@if($errors->any())<div class="mb-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $action }}" class="space-y-5 rounded-2xl border border-white/10 bg-[#0f0f11] p-6">
    @csrf
    @if($method !== 'POST') @method($method) @endif
    <div><label class="mb-2 block text-sm text-gray-400">Proyecto</label><select name="proyecto_id" required class="w-full rounded-lg border border-white/10 bg-black px-3 py-2.5 text-white">@foreach($proyectos as $proyecto)<option value="{{ $proyecto->id }}" @selected(old('proyecto_id', $bug?->proyecto_id) == $proyecto->id)>{{ $proyecto->nombre }}</option>@endforeach</select></div>
    <div><label class="mb-2 block text-sm text-gray-400">Título</label><input name="titulo" required maxlength="255" value="{{ old('titulo', $bug?->titulo) }}" class="w-full rounded-lg border border-white/10 bg-black px-3 py-2.5 text-white"></div>
    <div><label class="mb-2 block text-sm text-gray-400">Descripción</label><textarea name="descripcion" rows="5" class="w-full rounded-lg border border-white/10 bg-black px-3 py-2.5 text-white">{{ old('descripcion', $bug?->descripcion) }}</textarea></div>
    <div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm text-gray-400">Estado</label><select name="estado" required class="w-full rounded-lg border border-white/10 bg-black px-3 py-2.5 text-white">@foreach(['Reportado','Investigando','En desarrollo','En pruebas','Solucionado','Cerrado'] as $estado)<option @selected(old('estado', $bug?->estado ?? 'Reportado') === $estado)>{{ $estado }}</option>@endforeach</select></div><div><label class="mb-2 block text-sm text-gray-400">Prioridad</label><select name="prioridad" required class="w-full rounded-lg border border-white/10 bg-black px-3 py-2.5 text-white">@foreach(['Baja','Media','Alta'] as $prioridad)<option @selected(old('prioridad', $bug?->prioridad ?? 'Media') === $prioridad)>{{ $prioridad }}</option>@endforeach</select></div></div>
    <div><label class="mb-2 block text-sm text-gray-400">Fecha detectado</label><input type="date" name="fecha_detectado" value="{{ old('fecha_detectado', $bug?->fecha_detectado?->format('Y-m-d')) }}" class="rounded-lg border border-white/10 bg-black px-3 py-2.5 text-white"></div>
    <button class="rounded-xl bg-[#d61f2c] px-5 py-3 text-sm font-bold">Guardar bug</button>
</form>
