<?php

return [
    'ai' => [
        'enabled' => (bool) env('NEXUS_AI_ENABLED', false),
        'driver' => env('NEXUS_AI_DRIVER', 'openai_compatible'),
        'endpoint' => env('NEXUS_AI_ENDPOINT', 'https://api.openai.com/v1/chat/completions'),
        'api_key' => env('NEXUS_AI_API_KEY'),
        'model' => env('NEXUS_AI_MODEL', 'gpt-4o-mini'),
        'temperature' => (float) env('NEXUS_AI_TEMPERATURE', 0.1),
        'timeout' => (int) env('NEXUS_AI_TIMEOUT', 30),
        'max_steps' => (int) env('NEXUS_AI_MAX_STEPS', 5),
        'local' => [
            'python' => env('NEXUS_LOCAL_PYTHON', env('NEXUS_PYTHON_EXECUTABLE', 'python')),
            'script' => env('NEXUS_LOCAL_SCRIPT', 'scripts/nexus_infer.py'),
            'checkpoint' => env('NEXUS_AI_MODEL_PATH', env('NEXUS_LOCAL_CHECKPOINT', 'storage/app/nexus-model/latest.json')),
            'tokenizer' => env('NEXUS_AI_TOKENIZER_PATH', env('NEXUS_LOCAL_TOKENIZER', 'storage/app/nexus-model/tokenizer.json')),
            'max_context_tokens' => (int) env('NEXUS_LOCAL_MAX_CONTEXT_TOKENS', 2048),
            'max_new_tokens' => (int) env('NEXUS_LOCAL_MAX_NEW_TOKENS', 128),
            'temperature' => (float) env('NEXUS_LOCAL_TEMPERATURE', 0.7),
            'top_k' => (int) env('NEXUS_LOCAL_TOP_K', 40),
            'top_p' => (float) env('NEXUS_LOCAL_TOP_P', 0.9),
            'timeout' => (int) env('NEXUS_LOCAL_TIMEOUT', 30),
            'logits_cache_size' => (int) env('NEXUS_LOCAL_LOGITS_CACHE_SIZE', 1024),
            'quantization' => env('NEXUS_LOCAL_QUANTIZATION', 'none'),
        ],
        'python' => [
            'enabled' => (bool) env('NEXUS_PYTHON_ENABLED', false),
            'executable' => env('NEXUS_PYTHON_EXECUTABLE', 'python'),
            'working_directory' => env('NEXUS_PYTHON_WORKING_DIRECTORY', base_path()),
            'timeout' => (int) env('NEXUS_PYTHON_TIMEOUT', 30),
            'memory_path' => env('NEXUS_PYTHON_MEMORY_PATH', storage_path('app/nexus-ai/memory.json')),
            'memory_ttl' => (int) env('NEXUS_PYTHON_MEMORY_TTL', 1800),
            'memory_max_records' => (int) env('NEXUS_PYTHON_MEMORY_MAX_RECORDS', 50),
        ],
    ],
    'memory' => [
        'recent_messages' => (int) env('NEXUS_MEMORY_RECENT_MESSAGES', 8),
        'message_candidates' => (int) env('NEXUS_MEMORY_MESSAGE_CANDIDATES', 80),
        'relevant_messages' => (int) env('NEXUS_MEMORY_RELEVANT_MESSAGES', 6),
        'relevant_memories' => (int) env('NEXUS_MEMORY_RELEVANT_MEMORIES', 8),
        'engineering_memory_limit' => (int) env('NEXUS_ENGINEERING_MEMORY_LIMIT', 50),
        'engineering_memory_ttl_days' => (int) env('NEXUS_ENGINEERING_MEMORY_TTL_DAYS', 180),
    ],
    'modules' => [
        'proyectos' => ['label' => 'Proyectos', 'route' => 'proyectos.index'],
        'tareas' => ['label' => 'Tareas', 'route' => 'tareas.index'],
        'bugs' => ['label' => 'Bugs', 'route' => 'bugs.index'],
        'actualizaciones' => ['label' => 'Actualizaciones', 'route' => 'actualizaciones'],
        'usuarios' => ['label' => 'Usuarios', 'route' => 'usuarios'],
        'ia analisis' => ['label' => 'IA / Análisis', 'route' => 'asistente.index'],
    ],
    'states' => [
        'tareas' => ['Pendiente', 'En progreso', 'En revisión', 'Completado', 'Cancelado'],
        'bugs' => ['Reportado', 'Investigando', 'En desarrollo', 'En pruebas', 'Solucionado', 'Cerrado'],
    ],
    'rules' => [
        'scan_is_read_only' => true,
        'secrets_are_redacted' => true,
    ],
    'watch_directories' => [
        'app',
        'routes',
        'config',
        'database',
        'resources',
    ],
    'watch_excluded' => [
        '.env',
        'vendor/',
        'storage/',
        'bootstrap/cache/',
    ],
];
